export const config = {
  USERS_ENDPOINT: process.env.NEXT_PUBLIC_USERS_ENDPOINT as string,
  SENSORS_ENDPOINT: process.env.NEXT_PUBLIC_SENSORS_ENDPOINT as string,
  TELEMETRY_ENDPOINT: process.env.NEXT_PUBLIC_TELEMETRY_ENDPOINT as string,
  USER_RULES_ENDPOINT: process.env.NEXT_PUBLIC_USER_RULES_ENDPOINT as string,
  LOGIN_ENDPOINT: process.env.NEXT_PUBLIC_LOGIN_ENDPOINT as string,
};
